### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by slabgames** [DrMoriarty/godot-firebase-cloudmessaging#1]
Got this error report from Crashlytics
```

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void ru.mobilap.firebasecloudmessaging.FirebaseCloudMessaging.set_token(java.lang.String)' on a null object reference
       at ru.mobilap.firebasecloudmessaging.MyFirebaseMessagingService.onNewToken(MyFirebaseMessagingService.java:75)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.0.1:8)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(:6)
       at java.lang.Thread.run(Thread.java:919)

```

**Comment by DrMoriarty** [comment]
What is the exception text?

**Comment by slabgames** [comment]
@DrMoriarty updated

**Comment by DrMoriarty** [comment]
@slabgames fixed and updated plugin

**Comment by slabgames** [comment]
thanks for flash response
